Scan Docker Image with trivy

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -7,41 +7,56 @@ on:
 jobs:
   build-image:
     runs-on: ubuntu-latest
-
     steps:
-    - uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
-    - name: Set up Python 3.8
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3.8
-        
-    - name: Build image & push to docker hub
-      uses: mr-smithers-excellent/docker-build-push@v6
-      with:
-        image: sarvesh717/sands-of-time
-        tags: v2
-        registry: docker.io
-        dockerfile: Dockerfile
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }} 
+      - name: Set up Python 3.8
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.8
+
+      - name: Build image & push to docker hub
+        id: build_push
+        uses: mr-smithers-excellent/docker-build-push@v6
+        with:
+          image: sarvesh717/sands-of-time
+          tags: v2
+          registry: docker.io
+          dockerfile: Dockerfile
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+
+      - name: Scan Docker Image with Trivy
+        uses: aquasecurity/trivy-action@master
+        with:
+          image-ref: "sarvesh717/sands-of-time:v2"
+          severity: "CRITICAL,HIGH,MEDIUM"
+          exit-code: "1"
 
   deploy-container:
     needs: build-image
     runs-on: ubuntu-latest
     if: ${{ success() }}
     steps:
-    - name: executing remote ssh commands
-      uses: appleboy/ssh-action@v1.0.0
-      with:
-        host: ${{ secrets.EC2_HOST }}
-        username: ${{ secrets.EC2_USER }}
-        key: ${{ secrets.EC2_SSH_KEY }}
-        script: |
-            cd ~/Sands-Of-Time-Deployment
+      - name: Executing remote SSH commands for deployment
+        uses: appleboy/ssh-action@v1.0.0
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USER }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            echo "Changing to repository directory..."
+            cd ~/Sands-Of-Time-Deployment || { echo "Directory not found"; exit 1; }
+            echo "Pulling latest changes from GitHub..."
             git pull origin main
+            echo "Stopping existing containers..."
             sudo docker-compose down
+            echo "Pulling latest images from Docker Hub..."
             sudo docker-compose pull
+            echo "Listing Docker images..."
             sudo docker image ls
+            echo "Starting containers..."
             sudo docker-compose up -d
+            echo "Listing running containers..."
             sudo docker ps -a
